language: java
jdk:
  - oraclejdk8
before_script: 
  - chmod a+x ./mvnw
  - chmod a+x ./mvn
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V